# Generated by Django 4.0.3 on 2022-06-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-price',)},
        ),
    ]
